package bundle

import (
	"fmt"
	"sort"
	"strings"
)

func renderPatchText(document patchDocument) string {
	var builder strings.Builder
	fmt.Fprintf(&builder, "gooo-change-bundle-patch-v1\ndirection=%s\ndecision=%s\n", document.Direction, document.Decision)
	for _, operation := range document.Operations {
		fmt.Fprintf(&builder, "@@ path=%s operation=%s\n", operation.Path, operation.Operation)
		fmt.Fprintf(&builder, "preimage_digest=%s\npostimage_digest=%s\n", operation.PreimageDigest, operation.PostimageDigest)
		fmt.Fprintf(&builder, "preimage_base64=%s\npostimage_base64=%s\n", operation.PreimageBase64, operation.PostimageBase64)
	}
	return builder.String()
}

func renderEvaluator(intent Intent) string {
	var builder strings.Builder
	builder.WriteString("// Code generated by gooo-change-bundle; DO NOT EDIT.\n")
	builder.WriteString("package generated\n\n")
	fmt.Fprintf(&builder, "const Schema = %q\nconst CellCount = %d\n\n", IRSchema, FixedCells)
	builder.WriteString("const AuthoritativePlatformSource = \"github_api_immutable\"\n")
	builder.WriteString("const NonAuthoritativePlatformSource = \"self_authored_manifest\"\n\n")
	builder.WriteString("var Activities = [...]string{\n")
	for _, activity := range intent.Activities {
		fmt.Fprintf(&builder, "\t%q,\n", activity.ID)
	}
	builder.WriteString("}\n\n")
	builder.WriteString("func ExternalImmutabilityContradiction(externalImmutable, selfAuthoredImmutable bool) bool {\n")
	builder.WriteString("\treturn !externalImmutable && selfAuthoredImmutable\n")
	builder.WriteString("}\n\n")
	builder.WriteString("func Resolve(refuted, unknown, externalImmutable, selfAuthoredImmutable bool) string {\n")
	builder.WriteString("\tif ExternalImmutabilityContradiction(externalImmutable, selfAuthoredImmutable) { refuted = true }\n")
	builder.WriteString("\tif refuted { return \"REFUTED\" }\n")
	builder.WriteString("\tif unknown { return \"UNKNOWN\" }\n")
	builder.WriteString("\treturn \"CLOSED\"\n")
	builder.WriteString("}\n")
	return builder.String()
}

func renderDossier(intent Intent, proposal Proposal, authority AuthorityReceipt, snapshot, post treeSnapshot, decision string, findings []Finding, unknowns []UnknownTuple, targets []TargetEntry, patchRoundTrip, rollbackRoundTrip bool) string {
	var builder strings.Builder
	builder.WriteString("# Gooo Change Bundle dossier\n\n")
	fmt.Fprintf(&builder, "- decision: `%s`\n- source tree digest: `%s`\n- intent digest: `%s`\n- proposal digest: `%s`\n- authority receipt digest: `%s`\n- preimage tree digest: `%s`\n- postimage tree digest: `%s`\n\n", decision, snapshot.Manifest.SourceDigest, intent.SourceDigest, proposal.ProposalDigest, authority.ReceiptDigest, snapshot.Manifest.SourceDigest, post.Manifest.SourceDigest)
	builder.WriteString("## Actuator boundary\n\n")
	builder.WriteString("This product materializes evidence and reversible change data only. It does not apply a patch or write the input repository.\n\n")
	builder.WriteString("| operation | value |\n|---|---:|\n")
	builder.WriteString("| repository_writes | `0` |\n| local_test_executions | `0` |\n| cross_project_required_gates | `0` |\n| apply_authorized | `false` |\n| commit_authorized | `false` |\n| push_authorized | `false` |\n| pull_request_authorized | `false` |\n| merge_authorized | `false` |\n\n")
	builder.WriteString("## External platform precedence\n\n")
	builder.WriteString("The external GitHub API immutability observation is authoritative. A self-authored release-manifest claim is non-authoritative; `external_immutable=false` with `self_authored_immutable=true` is a canonical `REFUTED` contradiction.\n\n")
	builder.WriteString("## Targets\n\n")
	builder.WriteString("| path | operation | preimage | postimage | hunks |\n|---|---|---|---|---:|\n")
	for _, target := range targets {
		fmt.Fprintf(&builder, "| `%s` | `%s` | `%s` | `%s` | %d |\n", target.Path, target.Operation, target.PreimageDigest, target.PostimageDigest, target.HunkCount)
	}
	if len(targets) == 0 {
		builder.WriteString("| _none_ | — | — | — | 0 |\n")
	}
	fmt.Fprintf(&builder, "\n- patch round-trip: `%t`\n- rollback round-trip: `%t`\n- fixed denominator: `%d cells / %d activities`\n\n", patchRoundTrip, rollbackRoundTrip, FixedCells, FixedActivities)
	builder.WriteString("## Findings\n\n")
	if len(findings) == 0 {
		builder.WriteString("No findings; the bundle is `CLOSED` under the declared preconditions.\n\n")
	} else {
		for _, finding := range findings {
			path := finding.Path
			if path == "" {
				path = "—"
			}
			fmt.Fprintf(&builder, "- `%s` `%s` path `%s`: %s\n", finding.State, finding.Code, path, finding.Reason)
		}
		builder.WriteString("\n")
	}
	if len(unknowns) > 0 {
		builder.WriteString("## UNKNOWN operational coordinates\n\n")
		for _, unknown := range unknowns {
			fmt.Fprintf(&builder, "- stage: `%s`; step: `%s`; reason: `%s`; unknown_class: `%s`; next_operation: `%s`; blocked_by: `%s`\n", unknown.Stage, unknown.Step, unknown.Reason, unknown.UnknownClass, unknown.NextOperation, strings.Join(unknown.BlockedBy, ","))
		}
		builder.WriteString("\n")
	}
	builder.WriteString("## Fixed activities\n\n")
	activities := append([]Activity(nil), intent.Activities...)
	sort.Slice(activities, func(i, j int) bool { return activities[i].Ordinal < activities[j].Ordinal })
	for _, activity := range activities {
		fmt.Fprintf(&builder, "%d. `%s` (%s/%s) — `%s -> %s`\n", activity.Ordinal, activity.ID, activity.ProofChoice, activity.IndicatorClass, activity.Input, activity.Output)
	}
	return builder.String()
}
